using System.Collections.Generic;

namespace TraderCAD
{
    public static class Equities
    {
        public static readonly Dictionary<string, string> Equity = new()
        {
            ["AAPL"] = "Apple Inc.",
            ["ABT"] = "Abbott Laboratories",
            ["ADBE"] = "Adobe Inc.",
            ["AMGN"] = "Amgen Inc.",
            ["AMZN"] = "Amazon.com, Inc.",
            ["AT"] = "AT&T",
            ["AVGO"] = "Broadcom Inc.",
            ["AXP"] = "American Express Company",
            ["AZN"] = "AstraZeneca PLC",
            ["AZSEY"] = "Allianz SE",
            ["BA"] = "The Boeing Company",
            ["BRK-B"] = "Berkshire Hathaway Inc.",
            ["C"] = "Citigroup",
            ["CMCSA"] = "Comcast Corporation",
            ["COST"] = "Costco Wholesale Corp",
            ["CRM"] = "SalesForce com Inc.",
            ["CSCO"] = "Cisco Systems Inc.",
            ["CVX"] = "Chevron",
            ["DIS"] = "The Walt Disney Company",
            ["FB"] = "Facebook Inc.",
            ["GE"] = "General Electric Company",
            ["GOOGL"] = "Alphabet Inc Class A",
            ["GSK"] = "GlaxoSmithKline PLC",
            ["HD"] = "The Home Depot Inc.",
            ["HON"] = "Honeywell International Inc.",
            ["IBM"] = "IBM Corp",
            ["INTC"] = "Intel Corp",
            ["JNJ"] = "Johnson & Johnson",
            ["JPM"] = "JPMorgan Chase",
            ["KO"] = "The Coca-Cola Company",
            ["LLY"] = "Eli Lilly & Co",
            ["LMT"] = "Lockheed Martin Corporation",
            ["LRLCY"] = "L'Oréal S.A.",
            ["LVMUY"] = "LVMH",
            ["MA"] = "Mastercard Inc.",
            ["MCD"] = "McDonalds Corp",
            ["MMM"] = "3M Company",
            ["MRK"] = "Merck & Co Inc.",
            ["MSFT"] = "Microsoft",
            ["NFLX"] = "Netflix Inc.",
            ["NKE"] = "NIKE Inc.",
            ["NVDA"] = "NVIDIA Corporation",
            ["NVS"] = "Novartis AG",
            ["ORCL"] = "Oracle Corporation",
            ["PEP"] = "PepsiCo Inc.",
            ["PFE"] = "Pfizer Inc.",
            ["PG"] = "The Procter & Gamble Company",
            ["PM"] = "Philip Morris International Inc.",
            ["PYPL"] = "PayPal Holdings Inc.",
            ["QCOM"] = "Qualcomm Incorporated",
            ["RHHBY"] = "Roche Holding AG",
            ["RY"] = "Royal Bank of Canada",
            ["SBUX"] = "Starbucks Corporation",
            ["SIEGY"] = "Siemens",
            ["SNY"] = "Sanofi",
            ["TD"] = "The Toronto Dominion Bank",
            ["TSM"] = "TSMC Ltd",
            ["TXN"] = "Texas Instruments Incorporated",
            ["UL"] = "Unilever PLC",
            ["UNH"] = "UnitedHealth Group Inc.",
            ["UNP"] = "Union Pacific Corp",
            ["UTX"] = "United Technologies Corporation",
            ["V"] = "Visa Inc.",
            ["VZ"] = "Verizon Communications Inc.",
            ["WFC"] = "Wells Fargo",
            ["WMT"] = "Walmart Inc.",
            ["XOM"] = "Exxon Mobil Corporation",
        };
    }
}